// Interface automatically generated by schemas-to-ts

export interface BlogPost {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title?: string;
    description?: string;
    body?: string;
    imageId?: string;
  };
}
export interface BlogPost_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  description?: string;
  body?: string;
  imageId?: string;
}

export interface BlogPost_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  description?: string;
  body?: string;
  imageId?: string;
}

export interface BlogPost_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  description?: string;
  body?: string;
  imageId?: string;
}
